 python3 cifar10.py --loss SoftmaxLoss --openmetric possibility
 python3 cifar10.py --loss CenterLoss --openmetric possibility
 python3 cifar10.py --loss CenterLoss --openmetric distance
 python3 cifar10.py --loss ArcFaceLoss --openmetric possibility
 python3 cifar10.py --loss ArcFaceLoss --openmetric cosine
 python3 cifar10.py --loss NormFaceLoss --openmetric possibility
 python3 cifar10.py --loss NormFaceLoss --openmetric cosine
 python3 cifar10.py --loss PSoftmaxLoss --openmetric possibility
 python3 cifar10.py --loss PSoftmaxLoss --openmetric norm
 python3 cifar10.py --loss PSoftmaxLoss --openmetric energy
